version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Installing Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Installing Back-End Dependencies
          command: |
            npm run backend:install
      - run:
          name: Building Front-End
          command: |
            npm run frontend:build
      - run:
          name: Building Back-End
          command: |
            npm run backend:build
      - run:
          name: Deploying Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploying Back-End
          command: |
            npm run backend:deploy
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
